source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

target 'terrible-player' do
  pod 'AFNetworking', "~> 1.2"   # can't use 2.x with restkit, will upgrade when available.
  pod 'RestKit', '~> 0.25.0'
  pod 'TPKeyboardAvoiding', "~> 1.3"
end
