source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.1'
inhibit_all_warnings!

target 'terrible-player' do
  pod 'AFNetworking', "~> 1.2"   # can't use 2.x with restkit, will upgrade when available.
  pod 'RestKit', '~> 0.25.0'
  pod 'TPKeyboardAvoiding', "~> 1.3"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET' # inherit
    end
  end
end
